In [3]:
import numpy as np
import pandas as pd

class MLR:

    def __init__(self, x, y):
        
        self.X = np.array(x, dtype=float) #Saves the x values entered as a NumPy matrix
        self.y = np.array(y, dtype=float).reshape(-1, 1) #Saves the y values and turns it into a column vector with n rows (amount of y values).
        self.n, self.k = self.X.shape #Saving self.n as the number of observations and self.k as the number of predictors using '.shape'.
        self.y_bar = float(np.mean(self.y))

#Method 1: 

    def LS_est(self):
        
        self.X_aug = np.column_stack((np.ones(self.n), self.X)) #Builds the X matrix by adding ones in the left-most column.
        XtX = self.X_aug.T @ self.X_aug #Computing (X'X)^(-1) X'y (beta_hat) step by step.
        XtX_inv = np.linalg.inv(XtX)
        Xty = self.X_aug.T @ self.y
        self.beta_hat = XtX_inv @ Xty

        return self.beta_hat #Returns a column vector containing alpha first, followed by the the beta(s) (slope coefficents).

#Method 2: 

    def R2(self):
      
        self.LS_est() #Run LS_est to find alpha and beta values in self.beta_hat.

        y_hat = self.X_aug @ self.beta_hat #Find the fitted values by computing (X_aug)(beta_hat).
        
        SSE = 0.0
        SST = 0.0
        for i in range(self.n): #Summing to find SSE and SST respectively for the R^2 value
            SSE += (self.y[i,0] - y_hat[i,0])**2 #Using index [i,0] for the ith entry of column 0 (first and only column of self.y and y_hat with 'self.n many' rows).
            SST += (self.y[i,0] - self.y_bar)**2  
        return (1 - SSE/SST)

# Method 3 

    def MSE(self):
        
        self.LS_est() #Again run LS.est for the alpha and beta values.
        
        y_hat = self.X_aug @ self.beta_hat #Calculate the fitted values again.

        SSE = 0.0
        for i in range(self.n): #Summing to find SSE value again.
            SSE += (self.y[i,0] - y_hat[i,0])**2 
          
        MSE = SSE/(self.n - self.k - 1) #Running this will return the MSE value as a float.

        return MSE
   





In [4]:
#Additional Tasks

#Task A


data = pd.read_excel("SD.xlsx") #Reading the excel data.
np_data=np.array(data)
y=np_data[:,0]  
x=np_data[:,1:3]
model = MLR(x,y)
print("Here are the results for Task A (reading data for Excel file 'SD'):")
print("")
print(model.LS_est())
print(model.MSE())
print(model.R2())
print("")


#Task B


ID=101043434
np.random.seed(ID) 
n=40
sigma=20
error=sigma*np.random.normal(0,1,n) 
x1=np.random.uniform(1,2,n)
x2=np.random.uniform(3,6,n) 

alpha=2025

beta1=27
beta2=-13


y_=alpha+beta1*x1+beta2*x2+error
x_ = np.column_stack((x1.reshape(n, 1), x2.reshape(n,1))) #Making x a (40 x 2) matrix by reshaping x1 and x2 as column vectors and stacking them.
model2 = MLR(x_,y_)
print("Here are the results for Task B (generated synthetic data with given parameters):")
print("")
print(model2.LS_est())
print(model2.MSE())
print(model2.R2())


Here are the results for Task A (reading data for Excel file 'SD'):

[[ 9.12667785]
 [-0.07240643]
 [ 0.20282116]]
0.4374686571159977
0.8492138369517719

Here are the results for Task B (generated synthetic data with given parameters):

[[2010.46573232]
 [  29.77724007]
 [ -10.35846214]]
622.8933405462803
0.2532941546025905


## Summary of Results

## Task A:

For my least-squares estimates I got the following results: $$\hat{\alpha} = 9.12667785, \enspace \hat{\beta_1} = -0.07240643, \enspace  \hat{\beta_2} =  0.20282116$$
<br>

These values are indicated by the first, second and third row entry of the column vector printed in the results above (from Task A).
I also got:
<br>

$$MSE = 0.4374686571159977, \enspace R^2 = 0.8492138369517719$$
<br> 

These values correspond to the printed values after the column vector respectively.



## Task B:

For my least-squares estimates I got the following results: $$\hat{\alpha} = 2010.46573232, \enspace \hat{\beta_1} =  29.77724007, \enspace  \hat{\beta_2} =  -10.35846214$$
<br>

Again, these values are indicated by the first, second and third row entry of the column vector printed in the results above (from Task B), and should be close to the given parameters $\alpha = 2025$, $\beta_1 = 27$, and $\beta_3 = -13$.
I also got:

$$MSE = 622.8933405462803, \enspace R^2 = 0.2532941546025905$$
<br> 

Again, these values correspond to the printed values after the column vector respectively. This $MSE$ value isn't the best as it should be approximately $\sigma^2 = 20^2 = 400$, so it is off by approximately $200$.



## USER GUIDE

## Class Initialiser MLR

To use it, create an instance of the class by calling, for example, 'model = MLR(x, y)'. Here, x is an $(n \times k)$ matrix (entered as the example seen below*) with each column representing $n$ observations from one of $k$ predictor variables. y can either be a 1D array of shape $(n,)$ or a 2D array of shape $(n, 1)$, where each y value is interpreted as a sample observation of a response variable (see example**). In the case a 1D array of shape $(n,)$ is entered, the 'reshape' command in the initialiser will turn it into a column vector (2D array) for the matrix calculations later. 
<br>

The number of rows of x, and the number of y values entered must match otherwise there will be an error.

    *  x = ([[1, 2],[3,4]])  #with column 1 as (1,3) and column 2 as (2,4). In other words you enter x row by row where each row represents an observation from k predictor variables.
<br>

    **  y = [5,6]  #in this example y is a 1D array.

## Method 1 – LS_est

This method calculates and returns the intercept $\hat{\alpha}$ (first entry of the column vector), as well as the slopes $\hat{\beta_i}, (i = 1,...,k)$ (the rest of the entries in the column vector).
It performs some matrix calculations in NumPy to get this column vector ('self.beta_hat', a 2D array of shape $(k+1,1)$) and returns it.

To use it, once you've created an instance of the class (e.g. 'model' from above), you could call, for example, 'print(model.LS_est())' to display the column vector with all of the $\alpha$ and $\beta_i$'s as specified above. 
<br>

## Method 2 – R2

This computes and returns the $R^2$ value. Call 'model.R2()' to get the $R^2$ value, and you could then print/save the value in the same fashion as previous methods (e.g. 'print(model.R2())').

<br>

## Method 3 – MSE


This method calculates and returns the Mean Squared Error (MSE). Continuing our example, you could call 'model.MSE()' to get the value of MSE, and print/save the value in the same fashion as previous methods (e.g. 'print(model.MSE())').
